
import { Truck } from './types.ts';

export const initialTrucks: Truck[] = [
  // ZONA I
  { id: 'IV-2638', name: 'IV-2638', type: 'Autobomba', zone: 'ZONA I', station: 'Estación I Puerto Madero', officer: { hierarchy: 'Capitan', name: 'Schreiner', lp: '1156528448' }, personnel: 8, personnelList: [], status: 'Para Servicio' },
  { id: 'FZ-2666', name: 'FZ-2666', type: 'Unidad Liviana', zone: 'ZONA I', station: 'Estación I Puerto Madero', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2105', name: 'FR-2105', type: 'Unidad Liviana', zone: 'ZONA I', station: 'Estación I Puerto Madero', officer: { hierarchy: 'Bro. Cdo', name: 'Cano', lp: '1133887190' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
  { id: 'BICICLETA-276', name: 'BICICLETA-276', type: 'Bicicleta', zone: 'ZONA I', station: 'Estación I Puerto Madero', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Para Servicio' },
  { id: 'BICICLETA-277', name: 'BICICLETA-277', type: 'Bicicleta', zone: 'ZONA I', station: 'Estación I Puerto Madero', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Para Servicio' },
  { id: 'POLARIS-6441', name: 'POLARIS-6441', type: 'Cuatriciclo', zone: 'ZONA I', station: 'Estación I Puerto Madero', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'BICICLETA-275', name: 'BICICLETA-275', type: 'Bicicleta', zone: 'ZONA I', station: 'Estación I Puerto Madero', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'YAM-3981', name: 'YAM-3981', type: 'Cuatriciclo', zone: 'ZONA I', station: 'Estación I Puerto Madero', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'POLARIS-3236', name: 'POLARIS-3236', type: 'Cuatriciclo', zone: 'ZONA I', station: 'Estación I Puerto Madero', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  
  { id: 'IV-2640', name: 'IV-2640', type: 'Autobomba', zone: 'ZONA I', station: 'Estación II Patricios', officer: { hierarchy: 'Teniente', name: 'Guerrero', lp: '1159704458' }, personnel: 3, personnelList: [], status: 'Para Servicio' },
  { id: 'IV-9005', name: 'IV-9005', type: 'Cisterna', zone: 'ZONA I', station: 'Estación II Patricios', officer: { hierarchy: 'Teniente', name: 'Candia', lp: '1140369578' }, personnel: 3, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2107', name: 'FR-2107', type: 'Unidad Liviana', zone: 'ZONA I', station: 'Estación II Patricios', officer: { hierarchy: 'Bro. Cdo.', name: 'Methey Doret', lp: '1130456522' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
  { id: 'BER-1168', name: 'BER-1168', type: 'Camioneta', zone: 'ZONA I', station: 'Estación II Patricios', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'MB-2672', name: 'MB-2672', type: 'Autobomba', zone: 'ZONA I', station: 'Estación II Patricios', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'ZONDA-2656', name: 'ZONDA-2656', type: 'Unidad Liviana', zone: 'ZONA I', station: 'Estación II Patricios', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'MB-2651', name: 'MB-2651', type: 'Autobomba', zone: 'ZONA I', station: 'Estación II Patricios', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'ZFD-2680', name: 'ZFD-2680', type: 'Unidad Liviana', zone: 'ZONA I', station: 'Estación II Patricios', officer: { hierarchy: 'Teniente', name: 'Fernandez', lp: '1131971135' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
  { id: 'CAT-DISEL', name: 'CAT-DISEL', type: 'Iluminación', zone: 'ZONA I', station: 'Estación II Patricios', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },

  { id: 'MB-9173-POMPEYA', name: 'MB-9173', type: 'Autobomba', zone: 'ZONA I', station: 'Destacamento Pompeya', officer: { hierarchy: 'Teniente', name: 'Fernandez', lp: '1131971135' }, personnel: 4, personnelList: [], status: 'Para Servicio' },

  { id: 'IV-2641', name: 'IV-2641', type: 'Autobomba', zone: 'ZONA I', station: 'Estación III Barracas', officer: { hierarchy: 'Capitan', name: 'Padilla', lp: '1170738620' }, personnel: 9, personnelList: [], status: 'Para Servicio' },
  { id: 'IV-9000', name: 'IV-9000', type: 'Cisterna', zone: 'ZONA I', station: 'Estación III Barracas', officer: { hierarchy: 'Bro. Sup', name: 'Gamarra', lp: '1133866449' }, personnel: 3, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2125', name: 'FR-2125', type: 'Unidad Liviana', zone: 'ZONA I', station: 'Estación III Barracas', officer: { hierarchy: 'Bro. Sup', name: 'Artaza', lp: '1193146505' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
  { id: 'ZONDA-2665', name: 'ZONDA-2665', type: 'Unidad Liviana', zone: 'ZONA I', station: 'Estación III Barracas', officer: { hierarchy: 'Bro. Sup', name: 'Blanco', lp: '1123652180' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'MB-2662', name: 'MB-2662', type: 'Autobomba', zone: 'ZONA I', station: 'Estación III Barracas', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'YAM-3982', name: 'YAM-3982', type: 'Cuatriciclo', zone: 'ZONA I', station: 'Estación III Barracas', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  
  { id: 'AGRALE-8371-BOCA', name: 'AGRALE-8371', type: 'Autobomba', zone: 'ZONA I', station: 'Destacamento Boca', officer: { hierarchy: 'Subtte', name: 'Rocha', lp: '1172304226' }, personnel: 5, personnelList: [], status: 'Para Servicio' },
  { id: 'MB-2660', name: 'MB-2660', type: 'Autobomba', zone: 'ZONA I', station: 'Destacamento Boca', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'ALLIGHT-4608', name: 'ALLIGHT-4608', type: 'Iluminación', zone: 'ZONA I', station: 'Destacamento Boca', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  
  { id: 'MB-2675-LUGANO', name: 'MB-2675', type: 'Autobomba', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: 'Capitan', name: 'Hermann', lp: '1172304229' }, personnel: 10, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2123', name: 'F.R.-2123', type: 'Unidad Liviana', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: 'Teniente', name: 'Cabanelas', lp: '1149451622' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'YAM-3986', name: 'YAM-3986', type: 'Cuatriciclo', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'MB-2674', name: 'MB-2674', type: 'Autobomba', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'ZONDA-2668-LUGANO', name: 'ZONDA-2668', type: 'Logística', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'BOTE-4751', name: '4751', type: 'Bote', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'YAM-3985', name: 'YAM-3985', type: 'Cuatriciclo', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'FC-2659', name: 'F.C-2659', type: 'Cisterna', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'IV-170', name: 'IV-170 P.M.A', type: 'Hidroelevador', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'ALLIGHT-LUGANO', name: 'ALLIGHT', type: 'Iluminación', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'MB-9174', name: 'MB-9174', type: 'Autobomba', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'FR-2826', name: 'F.R.-2826', type: 'Unidad Liviana', zone: 'ZONA I', station: 'Estación X Lugano', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },

  // ZONA II
  { id: 'IV-2635', name: 'IV-2635', type: 'Autobomba', zone: 'ZONA II', station: 'Estación IV Recoleta', officer: { hierarchy: 'Capitan', name: 'Nittolo', lp: '1140360922' }, personnel: 10, personnelList: [], status: 'Para Servicio' },
  { id: 'FC-2669', name: 'FC-2669', type: 'Cisterna', zone: 'ZONA II', station: 'Estación IV Recoleta', officer: { hierarchy: 'Subteniente', name: 'Ventieri', lp: '1132062610' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'AGRALE-8371', name: 'AGRALE-8371', type: 'Autobomba', zone: 'ZONA II', station: 'Estación IV Recoleta', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'FR-2126', name: 'F.R. 2126', type: 'Unidad Liviana', zone: 'ZONA II', station: 'Estación IV Recoleta', officer: { hierarchy: 'Bro. Calif.', name: 'Ruiz Diaz', lp: '1155707456' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
  { id: 'BER-1166', name: 'BER-1166', type: 'Camioneta', zone: 'ZONA II', station: 'Estación IV Recoleta', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'HIFEI-SN-RECOLETA', name: 'HIFEI S/N°', type: 'Gomon', zone: 'ZONA II', station: 'Estación IV Recoleta', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'CATERPILLAR', name: 'CATERPILLAR', type: 'Iluminación', zone: 'ZONA II', station: 'Estación IV Recoleta', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'YAM-3983-RECOLETA', name: 'YAM-3983', type: 'Cuatriciclo', zone: 'ZONA II', station: 'Estación IV Recoleta', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'IV-2642', name: 'IV-2642', type: 'Autobomba', zone: 'ZONA II', station: 'Estación IV Recoleta', officer: { hierarchy: 'Bro. Sup.', name: 'Galvan', lp: '1124711011' }, personnel: 1, personnelList: [], status: 'Fuera de Servicio' },
  
  { id: 'MB-2673-MISERERE', name: 'MB-2673', type: 'Autobomba', zone: 'ZONA II', station: 'Destacamento Miserere', officer: { hierarchy: 'Teniente', name: 'Correa', lp: '1124711010' }, personnel: 9, personnelList: [], status: 'Para Servicio' },

  { id: 'ZFD-2658', name: 'ZFD-2658', type: 'Sexticiclo', zone: 'ZONA II', station: 'Destacamento Retiro', officer: { hierarchy: 'Subteniente', name: 'Solari', lp: '1136466331' }, personnel: 3, personnelList: [], status: 'Para Servicio' },

  { id: 'MB-2653', name: 'MB-2653', type: 'Autobomba', zone: 'ZONA II', station: 'Estación V Cte. Gral. A. Vazquez', officer: { hierarchy: 'Capitan', name: 'Correa', lp: '1122930506' }, personnel: 8, personnelList: [], status: 'Para Servicio' },
  { id: 'FC-2667', name: 'FC-2667', type: 'Cisterna', zone: 'ZONA II', station: 'Estación V Cte. Gral. A. Vazquez', officer: { hierarchy: 'Teniente', name: 'Zurita', lp: '1133904613' }, personnel: 3, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2110', name: 'FR-2110', type: 'Unidad Liviana', zone: 'ZONA II', station: 'Estación V Cte. Gral. A. Vazquez', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'FR-2106', name: 'FR-2106', type: 'Unidad Liviana', zone: 'ZONA II', station: 'Estación V Cte. Gral. A. Vazquez', officer: { hierarchy: 'Bro. Sup', name: 'Moreno', lp: '1167933315' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
  { id: 'BER-1161', name: 'BER-1161', type: 'Camioneta', zone: 'ZONA II', station: 'Estación V Cte. Gral. A. Vazquez', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'HIFEI-SN-VAZQUEZ', name: 'HIFEI S/N°', type: 'Gomon', zone: 'ZONA II', station: 'Estación V Cte. Gral. A. Vazquez', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'MERCURY-4752', name: 'MERCURY-4752', type: 'Motor', zone: 'ZONA II', station: 'Estación V Cte. Gral. A. Vazquez', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'YAMAHA-4749', name: 'YAMAHA-4749', type: 'Gomon', zone: 'ZONA II', station: 'Estación V Cte. Gral. A. Vazquez', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'YAMAHA-3987', name: 'YAMAHA-3987', type: 'Cuatriciclo', zone: 'ZONA II', station: 'Estación V Cte. Gral. A. Vazquez', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'ALLIGHT-96', name: 'ALLIGHT-96', type: 'Iluminación', zone: 'ZONA II', station: 'Estación V Cte. Gral. A. Vazquez', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  
  { id: 'MB-2660-URQUIZA', name: 'MB-2660', type: 'Autobomba', zone: 'ZONA II', station: 'Destacamento Urquiza', officer: { hierarchy: 'Teniente', name: 'San Pedro', lp: '1156025496' }, personnel: 6, personnelList: [], status: 'Para Servicio' },
  { id: 'IV-2636', name: 'IV-2636', type: 'Autobomba', zone: 'ZONA II', station: 'Destacamento Urquiza', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'BIM-3067', name: 'BIM - 3067', type: 'Gomon', zone: 'ZONA II', station: 'Destacamento Urquiza', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  
  { id: 'MB-2672-SAAVEDRA', name: 'MB-2672', type: 'Autobomba', zone: 'ZONA II', station: 'Destacamento Saavedra', officer: { hierarchy: 'Teniente', name: 'Cardama', lp: '1149281460' }, personnel: 5, personnelList: [], status: 'Para Servicio' },
  
  { id: 'IV-2643', name: 'IV-2643', type: 'Autobomba', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: 'Teniente', name: 'Romeo', lp: '1170738811' }, personnel: 9, personnelList: [], status: 'Para Servicio' },
  { id: 'FORD-9052', name: 'FORD-9052', type: 'Hidroelevador', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: 'Bro. Sup.', name: 'Franco', lp: '1151410095' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'IV-9004', name: 'IV-9004', type: 'Cisterna', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: 'Teniente', name: 'Barros', lp: '1172304228' }, personnel: 3, personnelList: [], status: 'Para Servicio' },
  { id: 'JUMPER-2138', name: 'JUMPER 2138', type: 'U.A.R.', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: 'Bro. Cdo.', name: 'Picasso', lp: '1172304213' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2118', name: 'FR-2118', type: 'Unidad Liviana', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: 'Bro. Cdo', name: 'Mayor', lp: '1138938859' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
  { id: 'ALLIGHT-FIRMAPAZ', name: 'ALLIGHT', type: 'Iluminación', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'FORD-2681', name: 'FORD-2681', type: 'Usina', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'MB-2673-FIRMAPAZ', name: 'MB-2673', type: 'Autobomba', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'ZONDA-2666', name: 'ZONDA-2666', type: 'Unidad Liviana', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'MB-2675-FIRMAPAZ', name: 'MB-2675', type: 'Autobomba', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'CBER-1171', name: 'C.BER-1171', type: 'Unidad Liviana', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'IV-9051', name: 'IV-9051', type: 'Hidroelevador', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'MB-2677', name: 'MB-2677', type: 'Autobomba', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'FZ-2657', name: 'FZ-2657', type: 'Unidad Liviana', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'POLARIS-3237', name: 'POLARIS-3237', type: 'Sexticiclo', zone: 'ZONA II', station: 'Estación VI Crío. Mayor M. Firma Paz', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  
  { id: 'IV-2637-PALERMO', name: 'IV-2637', type: 'Autobomba', zone: 'ZONA II', station: 'Destacamento Palermo', officer: { hierarchy: 'Teniente', name: 'Farias', lp: '1170738812' }, personnel: 7, personnelList: [], status: 'Para Servicio' },
  
  { id: 'ZONDA-2668-CHACARITA', name: 'ZONDA-2668', type: 'Cisterna', zone: 'ZONA II', station: 'Destacamento Chacarita', officer: { hierarchy: 'Teniente', name: 'Reynoso', lp: '1165149966' }, personnel: 3, personnelList: [], status: 'Para Servicio' },
  
  // ZONA III
  { id: 'MB-2654', name: 'MB-2654', type: 'Autobomba', zone: 'ZONA III', station: 'Estación VII Flores', officer: { hierarchy: 'Capitan', name: 'Chiardi', lp: '1172304003' }, personnel: 10, personnelList: [], status: 'Para Servicio' },
  { id: 'VW-9319', name: 'VW-9319', type: 'Cisterna', zone: 'ZONA III', station: 'Estación VII Flores', officer: { hierarchy: 'Subtte.', name: 'Chocobar', lp: '1172304004' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'BER-1220', name: 'BER-1220', type: 'Unidad Liviana', zone: 'ZONA III', station: 'Estación VII Flores', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'FORD-9052-FLORES', name: 'FORD-9052', type: 'Hidroelevador', zone: 'ZONA III', station: 'Estación VII Flores', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'FR-2121', name: 'FR-2121', type: 'Unidad Liviana', zone: 'ZONA III', station: 'Estación VII Flores', officer: { hierarchy: 'Bro. Sup', name: 'Martino', lp: '1164887251' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'CAT-SN', name: 'CAT-S/N°', type: 'Iluminación', zone: 'ZONA III', station: 'Estación VII Flores', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'IV-2639-FLORES', name: 'IV-2639', type: 'Autobomba', zone: 'ZONA III', station: 'Estación VII Flores', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: '40HP-4595', name: '40 HP 4595', type: 'Semirrígido', zone: 'ZONA III', station: 'Estación VII Flores', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },

  { id: 'MB-346', name: 'MB-346', type: 'Autobomba', zone: 'ZONA III', station: 'Estación VIII Nueva Chicago', officer: { hierarchy: 'Capitan', name: 'Gimenez Almada', lp: '1123501490' }, personnel: 8, personnelList: [], status: 'Para Servicio' },
  { id: 'FC-2670', name: 'FC-2670', type: 'Cisterna', zone: 'ZONA III', station: 'Estación VIII Nueva Chicago', officer: { hierarchy: 'N/A', name: 'A/P EST. IX', lp: '1124774607' }, personnel: 2, personnelList: [], status: 'A Préstamo' },
  { id: 'FR-2129', name: 'F. R.-2129', type: 'Unidad Liviana', zone: 'ZONA III', station: 'Estación VIII Nueva Chicago', officer: { hierarchy: 'Bro. Cdo', name: 'Osman', lp: '1133886470' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'BER-1184', name: 'BER-1184', type: 'Camioneta', zone: 'ZONA III', station: 'Estación VIII Nueva Chicago', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'HIFEI-4726', name: 'HIFEI-4726', type: 'Bote', zone: 'ZONA III', station: 'Estación VIII Nueva Chicago', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'FTRANSIT-8353', name: 'F. TRANSIT-8353', type: 'Unidad Médica', zone: 'ZONA III', station: 'Estación VIII Nueva Chicago', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'FTRANSIT-8354', name: 'F. TRANSIT-8354', type: 'Unidad Médica', zone: 'ZONA III', station: 'Estación VIII Nueva Chicago', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'MB-347', name: 'MB-347', type: 'Autobomba', zone: 'ZONA III', station: 'Estación VIII Nueva Chicago', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'ALLIGHT-NUEVACHICAGO', name: 'ALLIGHT', type: 'Iluminación', zone: 'ZONA III', station: 'Estación VIII Nueva Chicago', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },

  { id: 'FC-2671-VELEZ', name: 'FC-2671', type: 'Autobomba', zone: 'ZONA III', station: 'Destacamento Velez Sarsfield', officer: { hierarchy: 'Teniente', name: 'Sanchez', lp: '1122641181' }, personnel: 3, personnelList: [], status: 'Para Servicio' },
  
  { id: 'IV-2745', name: 'IV-2745', type: 'Autobomba', zone: 'ZONA III', station: 'Estación IX Versailles', officer: { hierarchy: 'Teniente', name: 'Mahmud', lp: '1170738708' }, personnel: 7, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2122', name: 'FR-2122', type: 'Unidad Liviana', zone: 'ZONA III', station: 'Estación IX Versailles', officer: { hierarchy: 'Bro Cdo', name: 'Jaureguiberry', lp: '1167255867' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'BER-1212', name: 'BER-1212', type: 'Unidad Liviana', zone: 'ZONA III', station: 'Estación IX Versailles', officer: { hierarchy: 'Bro Cdo', name: 'Ordoñez', lp: '1170306621' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'HIFEI-450495', name: 'HIFEI-450495', type: 'Bote Semirrígido', zone: 'ZONA III', station: 'Estación IX Versailles', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'BIM-SN', name: 'BIM-S/N°', type: 'Bote Inflable', zone: 'ZONA III', station: 'Estación IX Versailles', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'NIGHTSHIFTER', name: 'NIGHTSHIFTER', type: 'Iluminación', zone: 'ZONA III', station: 'Estación IX Versailles', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'FC-2671-VERSAILLES', name: 'FC-2671', type: 'Cisterna', zone: 'ZONA III', station: 'Estación IX Versailles', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'MB-2676', name: 'MB-2676', type: 'Autobomba', zone: 'ZONA III', station: 'Estación IX Versailles', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },

  { id: 'MB-2674-DEVOTO', name: 'MB-2674', type: 'Autobomba', zone: 'ZONA III', station: 'Destacamento Devoto', officer: { hierarchy: 'Teniente', name: 'Acevedo', lp: '1172304253' }, personnel: 8, personnelList: [], status: 'Para Servicio' },

  { id: 'FC-2670-ALBARINO', name: 'FC-2670', type: 'Cisterna', zone: 'ZONA III', station: 'Estación XI Albariño', officer: { hierarchy: 'Capitan', name: 'Aranda', lp: '1131971411' }, personnel: 3, personnelList: [], status: 'Para Servicio' },
  { id: 'MB-9173-ALBARINO', name: 'MB 9173', type: 'Autobomba', zone: 'ZONA III', station: 'Estación XI Albariño', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'ALLIGHT-ALBARINO', name: 'ALLIGHT', type: 'Iluminación', zone: 'ZONA III', station: 'Estación XI Albariño', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'ZONDA-2665-ALBARINO', name: 'ZONDA-2665', type: 'Unidad Liviana', zone: 'ZONA III', station: 'Estación XI Albariño', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'IV-9051-ALBARINO', name: 'IV-9051', type: 'Hidroelevador', zone: 'ZONA III', station: 'Estación XI Albariño', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  
  // UNIDADES ESPECIALES
  { id: 'IV-2644', name: 'IV-2644', type: 'Autobomba', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 1 Caballito', officer: { hierarchy: 'Capitan', name: 'Ferreiro Vargas', lp: '1128929551' }, personnel: 5, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2111', name: 'F.R 2111 C/D', type: 'Unidad Liviana', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 1 Caballito', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'FR-2132', name: 'F.R 2132 C/S', type: 'Unidad Liviana', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 1 Caballito', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'HI-FEI-SN-CABALLITO', name: 'HI-FEI S/N°', type: 'Balsa Inflable', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 1 Caballito', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'SEM-GALLO-BIM-CABALLITO', name: 'SEM. GALLO BIM', type: 'Semirrígido', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 1 Caballito', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'MB-9157', name: 'MB-9157', type: 'Autobomba', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 1 Caballito', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'BIM-CORINA', name: 'BIM CORINA', type: 'Semirrígido', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 1 Caballito', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'HIGHFIELD', name: 'HIGHFIELD', type: 'Semirrígido', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 1 Caballito', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'ALLIGHT-CABALLITO', name: 'ALLIGHT', type: 'Iluminación', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 1 Caballito', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'MARINER-4725', name: 'MARINER 4725', type: 'Motor S/Emb', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 1 Caballito', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'JOHNSON-4479', name: 'JOHNSON 4479', type: 'Motor S/Emb', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 1 Caballito', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },

  { id: 'IV-9351', name: 'IV-9351', type: 'Autobomba', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 2 Saavedra', officer: { hierarchy: 'Capitan', name: 'Di Mango', lp: '1172304223' }, personnel: 8, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2130', name: 'F. R.-2130', type: 'Unidad Liviana', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 2 Saavedra', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'TOHATSU-4T', name: 'TOHATSU 4T', type: 'Embarcación', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 2 Saavedra', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'BIM-SN-SAAVEDRA', name: 'BIM S/N°', type: 'Semirrígido', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 2 Saavedra', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'HI-FEI-SN-SAAVEDRA', name: 'HI-FEI S/N°', type: 'Balsa Inflable', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 2 Saavedra', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'ALLIGHT-SAAVEDRA', name: 'ALLIGHT', type: 'Iluminación', zone: 'Unidades Especiales', station: 'Dto. G.E.R. 2 Saavedra', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },

  { id: 'OAI-718', name: 'OAI-718/2634 (F3)', type: 'Camioneta', zone: 'Unidades Especiales', station: 'Transporte Forense', officer: { hierarchy: 'Bro. Sup', name: 'Avelino', lp: '1168976081' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'OAI-717', name: 'OAI-717/2633 (F2)', type: 'Camioneta', zone: 'Unidades Especiales', station: 'Transporte Forense', officer: { hierarchy: 'Bro. Sup', name: 'Colarossi', lp: '1131970452' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'OAI-716', name: 'OAI-716/2632 (F1)', type: 'Camioneta', zone: 'Unidades Especiales', station: 'Transporte Forense', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'FHY-285', name: 'FHY-285-/1321 (F5)', type: 'Unidad Liviana', zone: 'Unidades Especiales', station: 'Transporte Forense', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'OSZ-875', name: 'OSZ-875/930 (F8)', type: 'Camioneta', zone: 'Unidades Especiales', station: 'Transporte Forense', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'AA-639-AM', name: 'AA-639-AM / 1188 (CB)', type: 'Camioneta', zone: 'Unidades Especiales', station: 'Transporte Forense', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  
  { id: 'IV-2639-BEFER', name: 'IV-2639', type: 'Autobomba', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: 'Inspector', name: 'Di Mango', lp: '1128929552' }, personnel: 8, personnelList: [], status: 'Para Servicio' },
  { id: 'MB-2652', name: 'MB-2652', type: 'Autobomba', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: 'Subinspector', name: 'Arbe', lp: '1128929553' }, personnel: 7, personnelList: [], status: 'Para Servicio' },
  { id: 'FORD-2655', name: 'FORD-2655', type: 'Bote', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: 'Ayudante', name: 'Tevez', lp: '1128929554' }, personnel: 3, personnelList: [], status: 'Para Servicio' },
  { id: 'MERCURY-4660', name: 'MERCURY 4660', type: 'Motor', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'HONDA-5184', name: 'HONDA 5184', type: 'Tornado', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'MERCURY-3102', name: 'MERCURY 3102', type: 'Motor', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'ALLIGHT-4661', name: 'ALLIGHT 4661', type: 'Iluminación', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Reserva' },
  { id: 'PEUGEOT-361', name: 'PEUGEOT-361', type: 'Transporte', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'FORD-2664', name: 'FORD-2664', type: 'Cisterna', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'IVECO-9360', name: 'IVECO 9360', type: 'Usina G.E.', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'FORD-2682', name: 'FORD-2682', type: 'Ranger', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'FD-7796', name: 'FD-7796', type: 'Cuatriciclo', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'YAMAHA-3975', name: 'YAMAHA-3975', type: 'Ranger', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },
  { id: 'FR-8356', name: 'F.R.-8356', type: 'Unidad Liviana', zone: 'Unidades Especiales', station: 'Div. B.E.FE.R.', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'Fuera de Servicio' },

  { id: 'JUMPER-2149', name: 'JUMPER-2149', type: 'Unidad Médica', zone: 'Unidades Especiales', station: 'Destacamento Sistema de Asistencia Critica', officer: { hierarchy: 'Subtte', name: 'Garcia', lp: '1138609314' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2114', name: 'F.R. 2114', type: 'Prensa', zone: 'Unidades Especiales', station: 'Destacamento Sistema de Asistencia Critica', officer: { hierarchy: 'Teniente', name: 'Freire', lp: '1137049338' }, personnel: 2, personnelList: [], status: 'Para Servicio' },

  { id: 'FR-2114-K9', name: 'K9', type: 'Búsqueda y Rescate', zone: 'Unidades Especiales', station: 'Estación Busqueda y Rescate K9', officer: { hierarchy: 'Capitan', name: 'Meaolo', lp: '1164093620' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  { id: 'BER-1167-K9', name: 'K.D.H.', type: 'Unidad Liviana', zone: 'Unidades Especiales', station: 'Estación Busqueda y Rescate K9', officer: { hierarchy: '', name: '', lp: '' }, personnelList: [], status: 'A Préstamo' },
  { id: 'FR-8356-K9', name: 'F.R.-8356', type: 'Unidad Liviana', zone: 'Unidades Especiales', station: 'Estación Busqueda y Rescate K9', officer: { hierarchy: 'Subtte.', name: 'Castelli', lp: '1123379552' }, personnel: 1, personnelList: [], status: 'Para Servicio' },

  { id: 'CUMP-2152', name: 'C.JUMP-2152', type: 'Camioneta', zone: 'Unidades Especiales', station: 'Brigada de Emergencias Especiales', officer: { hierarchy: 'Teniente', name: 'Day Vivas', lp: '1131970802' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2109', name: 'FR-2109', type: 'Camioneta', zone: 'Unidades Especiales', station: 'Brigada de Emergencias Especiales', officer: { hierarchy: 'Bro Sup.', name: 'Rivero', lp: '1151596298' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
  { id: 'CUMP-1170', name: 'C.JUMP. 1170', type: 'Camioneta', zone: 'Unidades Especiales', station: 'Brigada de Emergencias Especiales', officer: { hierarchy: 'Subtte', name: 'Ramirez', lp: '1122424171' }, personnel: 3, personnelList: [], status: 'Para Servicio' },
  
  // Jefatura y otros
  { id: 'FR-2139', name: 'FR-2139 (UPM)', type: 'Unidad Liviana', zone: 'Jefatura', station: 'Compania Técnico Pericial', officer: { hierarchy: 'Subteniente', name: 'Brandan', lp: '134480501' }, personnel: 3, personnelList: [], status: 'Para Servicio' },
  { id: 'FR-2117', name: 'FR-2117', type: 'Unidad Liviana', zone: 'Jefatura', station: 'Compania Técnico Pericial', officer: { hierarchy: 'Teniente', name: 'Douat', lp: '1140973788' }, personnel: 1, personnelList: [], status: 'Para Servicio' },

  { id: 'IV-2646', name: 'IV-2646 P.C.M', type: 'Autobomba', zone: 'Jefatura', station: 'O.C.O.B.', officer: { hierarchy: 'Teniente', name: 'Muzzicato', lp: '1133262437' }, personnel: 2, personnelList: [], status: 'Para Servicio' },
  
  { id: 'CBER-2104', name: 'C.BER - 2104', type: 'Unidad Liviana', zone: 'Jefatura', station: 'URIP Centro', officer: { hierarchy: 'Teniente', name: 'Rios', lp: '1139555916' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
  
  { id: 'FR-2131', name: 'FR-2131', type: 'Unidad Liviana', zone: 'Jefatura', station: 'URIP Norte', officer: { hierarchy: 'Subteniente', name: 'Pistoia', lp: '1167700709' }, personnel: 1, personnelList: [], status: 'Para Servicio' },
];

export const initialCrews: Record<string, string[]> = {
  'Estación I Puerto Madero': ['Capitan Schreiner', 'Bro. Cdo Cano'],
  'Estación II Patricios': ['Teniente Guerrero', 'Teniente Candia', 'Bro. Cdo. Methey Doret'],
  'Destacamento Pompeya': ['Teniente Fernandez'],
  'Estación III Barracas': ['Capitan Padilla', 'Bro. Sup Gamarra', 'Bro. Sup Artaza', 'Bro. Sup Blanco'],
  'Destacamento Boca': ['Subtte Rocha'],
  'Estación X Lugano': ['Capitan Hermann', 'Teniente Cabanelas'],
  'Estación IV Recoleta': ['Capitan Nittolo', 'Subteniente Ventieri', 'Bro. Calif. Ruiz Diaz', 'Bro. Sup. Galvan'],
  'Destacamento Miserere': ['Teniente Correa'],
  'Destacamento Retiro': ['Subteniente Solari'],
  'Estación V Cte. Gral. A. Vazquez': ['Capitan Correa', 'Teniente Zurita', 'Bro. Sup Moreno', 'Bro. Cal. Barrios'],
  'Destacamento Urquiza': ['Teniente San Pedro'],
  'Destacamento Saavedra': ['Teniente Cardama'],
  'Estación VI Crío. Mayor M. Firma Paz': ['Teniente Romeo', 'Bro. Sup. Franco', 'Teniente Barros', 'Bro. Cdo. Picasso', 'Bro. Cdo Mayor'],
  'Destacamento Palermo': ['Teniente Farias'],
  'Destacamento Chacarita': ['Teniente Reynoso'],
  'Estación VII Flores': ['Capitan Chiardi', 'Subtte. Chocobar', 'Bro. Sup Martino'],
  'Estación VIII Nueva Chicago': ['Capitan Gimenez Almada', 'Bro. Cdo Osman'],
  'Destacamento Velez Sarsfield': ['Teniente Sanchez'],
  'Estación IX Versailles': ['Teniente Mahmud', 'Bro Cdo Jaureguiberry', 'Bro Cdo Ordoñez'],
  'Destacamento Devoto': ['Teniente Acevedo'],
  'Estación XI Albariño': ['Capitan Aranda'],
  'Dto. G.E.R. 1 Caballito': ['Capitan Ferreiro Vargas'],
  'Dto. G.E.R. 2 Saavedra': ['Capitan Di Mango'],
  'Transporte Forense': ['Bro. Sup Avelino', 'Bro. Sup Colarossi', 'Tte Rodriguez'],
  'Div. B.E.FE.R.': ['Inspector Di Mango', 'Subinspector Arbe', 'Ayudante Tevez'],
  'Destacamento Sistema de Asistencia Critica': ['Subtte Garcia', 'Teniente Freire'],
  'Estación Busqueda y Rescate K9': ['Capitan Meaolo', 'Subtte. Castelli'],
  'Brigada de Emergencias Especiales': ['Teniente Day Vivas', 'Bro Sup. Rivero', 'Subtte Ramirez'],
  'Compania Técnico Pericial': ['Subteniente Brandan', 'Teniente Douat'],
  'O.C.O.B.': ['Teniente Filippi', 'Teniente Figueroa', 'Subteniente Casanova', 'Teniente Muzzicato', 'Teniente Monzon', 'Subtte. Perez'],
  'URIP Centro': ['Teniente Rios'],
  'URIP Norte': ['Subteniente Pistoia'],
};